version: '3'
services:
  rcalendar-mobile:
    build: .
    container_name: rcalendar-mobile
    restart: always
    ports:
      # 将宿主机的 80 端口映射到容器的 80 端口
      - "80:80"
    extra_hosts:
      # 允许容器通过 host.docker.internal 访问宿主机
      - "host.docker.internal:host-gateway"
